version: '3'

services:
  app:
    image: my-spring-boot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://healthclub.cxqfwrymhytt.us-east-1.rds.amazonaws.com/healthclub?characterEncoding=UTF-8&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin12345
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=healthclub
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin12345
      - MYSQL_ROOT_PASSWORD=admin12345
    ports:
      - "3306:3306"

